import Image from "next/image";
import ThemeToggle from "./components/ThemeToggle";
import Link from "next/link";
import ThreeSnowflakes from "./components/ThreeSnowFlakes";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <main className="min-h-screen bg-white dark:bg-[#1B062E] text-[#1B062E] dark:text-white">
      <div className="flex flex-col items-center justify-center pt-[250px] md:pt-[200px] pb-16 px-4 sm:px-6 lg:px-8">
      <h1 className="text-4xl sm:text-5xl font-bold text-center leading-relaxed max-w-5xl">
        Explore the Possibilities of <span className="text-[#7C21CC] border-b-4 border-b-[#678AFF] pb-[3px] leading-relaxed">AI Book Writing</span> with BookAI
      </h1>
      <p className="mt-4 text-lg sm:text-xl text-center max-w-2xl">
        Unleash the power of AI to create captivating books in minutes. Download, distribute wherever you want. Generate unlimited free books.
      </p>
      <div className="mt-8 flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
        <Link
        href="/playground"
          className="px-8 py-3 bg-gradient-primary animate-up text-white text-lg font-medium rounded-full focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#678AFF] dark:focus:ring-offset-[#1B062E]"
          aria-label="Get Started"
        >
          Get Started
        </Link>
        <Link
        href="/api"
          className="px-8 py-3 bg-gradient-primary animate-up text-white text-lg font-medium rounded-full hover:text-white focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#678AFF] dark:focus:ring-offset-[#1B062E]"
          aria-label="Get API Access"
        >
          Get API Access
        </Link>
      </div>
      <ThemeToggle />
      </div>
    </main>
    <ThreeSnowflakes />
    </>
  );
}
